// After `npm run build`: writes the verifying key into the Solana program,
// copies the prover files to the frontend, and makes a test proof (fixture)
// for the program's unit test.
import { createHash } from "node:crypto";
import { copyFileSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import * as snarkjs from "snarkjs";
import { commitment } from "./commitment.mjs";

const PROGRAM_VK = "../private_solana_exchange/programs/private_solana_exchange/src/zk/unshield_vk.rs";
const FRONTEND_ZK = "../frontend/public/zk";

const be32 = (n) => BigInt(n).toString(16).padStart(64, "0");
// Solana's alt_bn128 syscalls use EIP-197: big-endian, G2 as x.c1 ‖ x.c0 ‖ y.c1 ‖ y.c0.
const g1 = (p) => be32(p[0]) + be32(p[1]);
const g2 = (p) => be32(p[0][1]) + be32(p[0][0]) + be32(p[1][1]) + be32(p[1][0]);
const rustBytes = (hex) =>
  "[" + hex.match(/../g).map((b) => "0x" + b).join(", ") + "]";

const vk = JSON.parse(readFileSync("build/verification_key.json", "utf8"));
if (vk.protocol !== "groth16" || vk.curve !== "bn128" || vk.nPublic !== 3) {
  throw new Error("unexpected verification key");
}
const rust = `//! Generated by zk/scripts/export.mjs from zk/build/verification_key.json. Do not edit.

pub const ALPHA_G1: [u8; 64] = ${rustBytes(g1(vk.vk_alpha_1))};
pub const BETA_G2: [u8; 128] = ${rustBytes(g2(vk.vk_beta_2))};
pub const GAMMA_G2: [u8; 128] = ${rustBytes(g2(vk.vk_gamma_2))};
pub const DELTA_G2: [u8; 128] = ${rustBytes(g2(vk.vk_delta_2))};
pub const IC: [[u8; 64]; ${vk.IC.length}] = [
${vk.IC.map((p) => "    " + rustBytes(g1(p)) + ",").join("\n")}
];
`;
writeFileSync(PROGRAM_VK, rust);
console.log("wrote", PROGRAM_VK);

// The browser prover: snarkjs bundle + circuit wasm + proving key. The key is
// 82 MB, so it is split into parts under GitHub's 50 MB warning size; the
// browser downloads them, joins them and checks the SHA-256 in the manifest.
const PART_BYTES = 45 * 1024 * 1024;
mkdirSync(FRONTEND_ZK, { recursive: true });
copyFileSync("node_modules/snarkjs/build/snarkjs.min.js", `${FRONTEND_ZK}/snarkjs.min.js`);
copyFileSync("build/unshield_js/unshield.wasm", `${FRONTEND_ZK}/unshield.wasm`);
rmSync(`${FRONTEND_ZK}/unshield.zkey`, { force: true });
const zkey = readFileSync("build/unshield.zkey");
const parts = [];
for (let start = 0; start < zkey.length; start += PART_BYTES) {
  const name = `unshield.zkey.part${parts.length}`;
  writeFileSync(`${FRONTEND_ZK}/${name}`, zkey.subarray(start, start + PART_BYTES));
  parts.push(name);
}
const manifest = { parts, bytes: zkey.length, sha256: createHash("sha256").update(zkey).digest("hex") };
writeFileSync(`${FRONTEND_ZK}/unshield.json`, JSON.stringify(manifest, null, 2) + "\n");
console.log("copied the prover files to", FRONTEND_ZK, `(zkey in ${parts.length} parts)`);

// Fixture: 250 tokens committed, 100 withdrawn.
const balance = 250_000_000n;
const salt = 0x0f1e2d3c4b5a69788796a5b4c3d2e1f0n;
const amount = 100_000_000n;
const { hi, lo } = commitment(balance, salt);
const { proof, publicSignals } = await snarkjs.groth16.fullProve(
  { commitmentHi: hi, commitmentLo: lo, amount, balance, salt },
  "build/unshield_js/unshield.wasm",
  "build/unshield.zkey",
);
if (!(await snarkjs.groth16.verify(vk, publicSignals, proof))) throw new Error("fixture proof invalid");
const fixture = {
  a: g1(proof.pi_a),
  b: g2(proof.pi_b),
  c: g1(proof.pi_c),
  fingerprint: be32(hi).slice(32) + be32(lo).slice(32),
  amount: amount.toString(16).padStart(16, "0"),
};
writeFileSync("build/fixture.json", JSON.stringify(fixture, null, 2));
console.log("wrote build/fixture.json");
process.exit(0);
